version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql-spring-hotel
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - spring-hotel-data:/var/lib/mysql

volumes:
  spring-hotel-data: